"use client";
import RegistrationForm from "@/components/RegistrationForm/RegistrationForm";
import GoogleRecaptchaProvider from "@/components/GoogleCaptchaWrapper";
// export const metadata = {
//   title: "Register",
//   description: "Generated by create next app",
// };
export default function page() {
  return (
    <GoogleRecaptchaProvider>
      <div>
        <RegistrationForm />
      </div>
    </GoogleRecaptchaProvider>
  );
}
