import "./globals.css";
import { Inter } from "next/font/google";
import NavBar from "@/components/NavBar/NavBar";
import Footer from "@/components/Footer/Footer";
import AuthProvider from "@/components/providers/authProvider";
import GlobalState from "@/components/context";
import Provider from "@/components/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Marechal Djelfa",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <Provider>
          <AuthProvider>
            <GlobalState>
              <NavBar />
              {children}
              <Footer />
            </GlobalState>
          </AuthProvider>
        </Provider>
      </body>
    </html>
  );
}
